FROM python:3.12

RUN pip install \
    scanpy \
    cellxgene-census \
    anndata \
    numpy \
    pandas \
    scipy \
    scikit-learn \
    statsmodels \
    matplotlib \
    seaborn \
    tqdm \
    natsort \
    h5py \
    tables
